#####################################
#      Automate your workflow       #
#####################################

# This workflow will create a NPM package and a new release

name: Publish and release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:

  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-gpr:
    runs-on: ubuntu-latest

    needs: update_release_draft

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
